# 🐍 Live #1 — CSV Básico para Iniciantes em Python

**@mgdossantos** · Dia 7/30

Bem-vinda! Nesta live você vai aprender:
- O que é um arquivo CSV
- Como usar o Google Colab
- Como ler dados com Python usando pandas
- Como extrair insights reais de dados de vendas
- Gerar um gráfico de vendas

📁 **Dataset:** [automated_sales_report](https://github.com/mgdossantos/automated_sales_report)

💻 **Quer instalar Python no seu computador?** Assista ao vídeo de instalação no canal!

---

## 📌 Bloco 1 — O que é o Google Colab?

O **Google Colab** é um ambiente de programação que roda direto no navegador.
Você não precisa instalar nada no computador.

É como um documento do Google, só que em vez de texto você escreve **código Python** e roda na hora.

**Como funciona:**
- Cada bloco cinza abaixo é uma **célula de código**
- Clique no botão ▶️ à esquerda (ou `Shift + Enter`) para rodar
- O resultado aparece logo abaixo da célula

Vamos testar! Rode a célula abaixo 👇

In [ ]:
# Teste rápido — rode essa célula!
print("Olá! Python funcionando no Google Colab 🐍")
nome = "Marcela"
idade = 42
print(nome, "voce tem ", idade, "anos!!")

Olá! Python funcionando no Google Colab 🐍
Marcela voce tem  42 anos!!

---
## 📌 Bloco 2 — O que é um CSV?

**CSV** = Comma-Separated Values (Valores Separados por Vírgula)

É um arquivo de texto simples onde:
- Cada **linha** é uma linha da tabela
- Cada **coluna** é separada por vírgula

Exemplo:
```
date,product,category,quantity,price
2024-01-15,Laptop,Electronics,2,999.99
2024-01-16,Mouse,Electronics,5,29.99
```

💡 Toda planilha Excel pode ser salva como CSV. Sistemas de vendas exportam CSV. É o formato mais comum de dados no mundo real.

---

---
## 📌 Bloco 3 — Lendo o CSV com pandas

**pandas** é a biblioteca do Python feita para trabalhar com dados em tabela.
Como se fosse o Excel do Python.

`df` vem de **DataFrame** — o nome que o pandas dá para uma tabela.

In [ ]:
# Importando a biblioteca pandas
import pandas as pd

url = 'https://raw.githubusercontent.com/mgdossantos/automated_sales_report/main/data/sales.csv'
df = pd.read_csv(url)
print("Dados carregados! ✅")

Dados carregados! ✅

In [ ]:
# Visualizando a tabela completa
print(df)

          date   product     category  quantity  price
0   2024-01-01    Laptop  Electronics         2   1200
1   2024-01-03     Mouse  Electronics         5     25
2   2024-01-04  Keyboard  Electronics         3     80
3   2024-02-01    Laptop  Electronics         1   1200
4   2024-02-03   Monitor  Electronics         2    300
5   2024-02-10     Mouse  Electronics        10     25
6   2024-03-02  Keyboard  Electronics         4     80
7   2024-03-05   Monitor  Electronics         3    300
8   2024-03-12    Laptop  Electronics         1   1200
9   2024-04-01     Mouse  Electronics         8     25
10  2024-04-06  Keyboard  Electronics         2     80
11  2024-04-15   Monitor  Electronics         1    300
12  2024-05-03    Laptop  Electronics         2   1200
13  2024-05-10     Mouse  Electronics         6     25
14  2024-05-18  Keyboard  Electronics         5     80

---
## 📌 Bloco 4 — Explorando os dados

Sempre que você não sabe o que tem dentro de um DataFrame, use `.head()`.
É como dar uma espiada nos dados antes de trabalhar com eles.

In [ ]:
# Quantas linhas e colunas?
print("Tamanho do dataset:")
print(df.shape)
print(f"→ {df.shape[0]} linhas e {df.shape[1]} colunas")

Tamanho do dataset:
(15, 5)
→ 15 linhas e 5 colunas

In [ ]:
# Quais são as colunas?
print("Colunas disponíveis:")
print(df.columns.tolist())

Colunas disponíveis:
['date', 'product', 'category', 'quantity', 'price']

In [ ]:
# Primeiras 5 linhas
print("Primeiras 5 linhas:")
df.head()

Primeiras 5 linhas:

         date   product     category  quantity  price
0  2024-01-01    Laptop  Electronics         2   1200
1  2024-01-03     Mouse  Electronics         5     25
2  2024-01-04  Keyboard  Electronics         3     80
3  2024-02-01    Laptop  Electronics         1   1200
4  2024-02-03   Monitor  Electronics         2    300

In [ ]:
# Tipo de dado de cada coluna
print("Tipos de dados:")
print(df.dtypes)
print()
print("💡 A coluna 'date' aparece como 'object' (texto), não como data.")
print("   Isso é muito comum em dados reais — vamos falar sobre isso em outra live!")

Tipos de dados:
date        object
product     object
category    object
quantity     int64
price        int64
dtype: object

💡 A coluna 'date' aparece como 'object' (texto), não como data.
   Isso é muito comum em dados reais — vamos falar sobre isso em outra live!

---
## 📌 Bloco 5 — Extraindo insights reais

Com as colunas `date`, `product`, `category`, `quantity` e `price` já conseguimos responder perguntas reais de negócio.

**Vamos criar a coluna de receita primeiro:**

In [ ]:
# Calculando a receita por transação
# receita = quantidade × preço
df['revenue'] = df['quantity'] * df['price']

print("Nova coluna 'revenue' criada! ✅")
df.head()

Nova coluna 'revenue' criada! ✅

         date   product     category  quantity  price  revenue
0  2024-01-01    Laptop  Electronics         2   1200     2400
1  2024-01-03     Mouse  Electronics         5     25      125
2  2024-01-04  Keyboard  Electronics         3     80      240
3  2024-02-01    Laptop  Electronics         1   1200     1200
4  2024-02-03   Monitor  Electronics         2    300      600

In [ ]:
# Receita total
receita_total = df['revenue'].sum()
print(f"💰 Receita total: R$ {receita_total:,.2f}")

💰 Receita total: R$ 10,845.00

In [ ]:
# Produto mais vendido por quantidade
print("📦 Produtos mais vendidos (por quantidade):")
print()
print(df.groupby('product')['quantity'].sum().sort_values(ascending=False))

📦 Produtos mais vendidos (por quantidade):

product
Mouse       29
Keyboard    14
Laptop       6
Monitor      6
Name: quantity, dtype: int64

In [ ]:
# Ticket médio por transação
ticket_medio = df['revenue'].mean()
print(f"🎯 Ticket médio por transação: R$ {ticket_medio:.2f}")

🎯 Ticket médio por transação: R$ 723.00

In [ ]:
# Resumo geral dos dados numéricos
print("📊 Resumo estatístico:")
df[['quantity', 'price', 'revenue']].describe().round(2)

📊 Resumo estatístico:

       quantity    price  revenue
count     15.00    15.00    15.00
mean       3.67   408.00   723.00
std        2.69   504.35   770.22
min        1.00    25.00   125.00
25%        2.00    52.50   220.00
50%        3.00    80.00   320.00
75%        5.00   750.00  1050.00
max       10.00  1200.00  2400.00

In [ ]:
# Calculando a receita total por produto
receita_por_produto = df.groupby('product')['revenue'].sum().sort_values(ascending=False)

print("💰 Receita por Produto (do maior para o menor):")
print(receita_por_produto)

💰 Receita por Produto (do maior para o menor):
product
Laptop      7200
Monitor     1800
Keyboard    1120
Mouse        725
Name: revenue, dtype: int64

## 🎯 Exercício ao vivo — Qual produto gerou mais receita? 💰

Olha a tabela acima e chuta no chat antes de rodar o gráfico!

---
## 📌 Bloco 6 — Gerando gráficos

Um gráfico de barras de receita por produto

In [ ]:
import plotly.express as px

# Convert the Series to a DataFrame so 'product' and 'revenue' become explicit columns
receita_por_produto_df = receita_por_produto.reset_index()
print(receita_por_produto_df)

    product  revenue
0    Laptop     7200
1   Monitor     1800
2  Keyboard     1120
3     Mouse      725

In [ ]:
fig = px.bar(
    receita_por_produto_df,
    x = "revenue",
    y="product", # Changed to 'product' as this is the correct column name
    title= "Receita por Produto", # Updated title to be relevant
    color ="product" # Changed to 'product' as this is the correct column name
)
fig.show()

---
## 🎉 Resumo da Live #1

Hoje você aprendeu:

✅ O que é o **Google Colab** e como usar

✅ O que é um **arquivo CSV** e por que ele existe

✅ Como ler um CSV com **pandas** (`pd.read_csv`)

✅ Como explorar dados com `.shape`, `.columns`, `.head()`, `.dtypes`

✅ Como calcular **receita**, agrupar por produto e categoria

✅ Como extrair o **mês** de uma coluna de data

✅ Como gerar o gráfico de receita por produto

---
✅ Praticou **5 exercícios** com análise real de dados


- 🔗 Me segue no Instagram: **@mgdossantos.prof**